title: Welcom to K Food Blog
author: kimphuongg
email: kimphuongg@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a food blog to share tips and tricks to cook good food by yourself. 
  You can also contribute to the food recipe collection in the comment section below.
  Stay tunned.
# social links
twitter_username: kimphuongg
github_username:  kimphuongg

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot
